name: Generate NCI resources report
on: [push]

jobs:
  runcode:
    runs-on: ubuntu-latest
    steps:
      - name: Run  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.PASSPHRASE}} 
          command_timeout: 60m
          script: |
              module use /g/data3/xp65/public/modules
              module load conda/analysis3
              cd /g/data/gb02/public/code/nci_resource_tools
              source ./env.sh
              cd notebooks
              quarto render dashboard.ipynb --execute --to html
      
