name: Scheduled Workflow

on:
  schedule:
    - cron: '30 2 * * *' # Runs every day at 2:30 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: |
          echo "hello github"
